
services:
  db:
    image: postgres:15
    container_name: notes_db
    environment:
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: notesdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    image: ${DOCKER_REGISTRY-}notessolutionapi
    build:
      context: .
      dockerfile: NotesSolution.API/Dockerfile
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=notesdb;Username=postgres;Password=postgrespw

volumes:
  pgdata: