
services:
  db:
    image: postgres:15
    container_name: notes_db
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: notesdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    image: ${DOCKER_REGISTRY-}notessolutionapi
    build:
      context: .
      dockerfile: NotesSolution.API/Dockerfile
    depends_on:
      - db
    environment:
      - ImageStorage__BaseUrl=https://localhost:8081/images
      - ApiSettings__Secret=${JWT_SECRET}
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=notesdb;Username=postgres;Password=${DB_PASSWORD}
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
        - "8080:8080"
        - "8081:8081"
    volumes:
      - ./app-images:/app/images

volumes:
  pgdata: